import random

objects = [
    {
"date": "2023-10-31",
"note": "Spacieuse maison familiale",
"rappel_hour": "14:00",
"country": "France",
"mail_specified": "contact@immobilier-exemple.com",
"city": "Paris",
"description": "Belle maison de 4 chambres à coucher avec jardin.",
"full_address": "123 Rue de la Maison, 75000 Paris",
"document_version": 1,
"title": "Maison à Paris",
"date_timestamp": 1667260800,
"zip_code": "75000",
"archived": False,
"datetime": "2023-10-31 14:00:00",
"expired": False,
"file": "property1.pdf",
"province": "Île-de-France",
"category_id": "1",
"last_update_timestamp": 1667260800,
"street": "Rue de la Maison",
"price": 500000.0,
"particulier": True,
"id": "property-1",
"state_id": "FR",
"lang": "fr",
"owner_tel": "01 234 567 890",
"rappel_date": "2023-11-15",
"rappel_date_timestamp": 1679097600,
"last_update_date": "2023-10-31",
"m_2": 180,
"website": "www.immobilier-exemple.com",
"tel_specified": True,
"owner_name": "Jean Dupont",
"last_update_datetime": "2023-10-31 14:00:00",
"created_by": "John Doe",
"picture": "picture1.jpg",
"url": "www.immobilier-exemple.com/property-1",
"address_number": "123",
"cert_peb_specified": True,
"sale": True,
"deleted": False,
"province_id": "IDF",
"category": "Maison",
"website_id": "1",
"country_id": "FR"
},

{
   "date": "2023-10-31",
   "note": "Appartement moderne en plein centre de Madrid",
   "rappel_hour": "15:30",
   "country": "Espagne",
   "mail_specified": "contact@immobilier-exemple.com",
   "city": "Madrid",
   "description": "Superbe appartement de 2 chambres au cœur de Madrid.",
   "full_address": "Calle de Madrid, 28001 Madrid",
   "document_version": 1,
   "title": "Appartement à Madrid",
   "date_timestamp": 1667260800,
   "zip_code": "28001",
   "archived": False,
   "datetime": "2023-10-31 15:30:00",
   "expired": False,
   "file": "property2.pdf",
   "province": "Comunidad de Madrid",
   "category_id": "2",
   "last_update_timestamp": 1667260800,
   "street": "Calle de Madrid",
   "price": 350000.0,
   "particulier": True,
   "id": "property-2",
   "state_id": "ES",
   "lang": "es",
   "owner_tel": "+34 123 456 789",
   "rappel_date": "2023-11-10",
   "rappel_date_timestamp": 1678684800,
   "last_update_date": "2023-10-31",
   "m_2": 100,
   "website": "www.immobilier-exemple.com",
   "tel_specified": True,
   "owner_name": "Maria López",
   "last_update_datetime": "2023-10-31 15:30:00",
   "created_by": "Ana García",
   "picture": "picture2.jpg",
   "url": "www.immobilier-exemple.com/property-2",
   "address_number": "123",
   "cert_peb_specified": True,
   "sale": True,
   "deleted": False,
   "province_id": "MD",
   "category": "Appartement",
   "website_id": "1",
   "country_id": "ES"
},

{
   "date": "2023-10-31",
   "note": "Luxurious Downtown San Francisco Condo",
   "rappel_hour": "14:30",
   "country": "United States",
   "mail_specified": "contact@realestate-example.com",
   "city": "San Francisco",
   "description": "Stunning 3-bedroom condo with city views in downtown San Francisco.",
   "full_address": "123 Market Street, San Francisco, CA 94105",
   "document_version": 1,
   "title": "Condo in San Francisco",
   "date_timestamp": 1667260800,
   "zip_code": "94105",
   "archived": False,
   "datetime": "2023-10-31 14:30:00",
   "expired": False,
   "file": "property3.pdf",
   "province": "California",
   "category_id": "3",
   "last_update_timestamp": 1667260800,
   "street": "Market Street",
   "price": 1500000.0,
   "particulier": True,
   "id": "property-3",
   "state_id": "CA",
   "lang": "en",
   "owner_tel": "+1 (123) 456-7890",
   "rappel_date": "2023-11-15",
   "rappel_date_timestamp": 1679097600,
   "last_update_date": "2023-10-31",
   "m_2": 180,
   "website": "www.realestate-example.com",
   "tel_specified": True,
   "owner_name": "John Smith",
   "last_update_datetime": "2023-10-31 14:30:00",
   "created_by": "Jane Doe",
   "picture": "picture3.jpg",
   "url": "www.realestate-example.com/property-3",
   "address_number": "123",
   "cert_peb_specified": True,
   "sale": True,
   "deleted": False,
   "province_id": "CA",
   "category": "Condo",
   "website_id": "2",
   "country_id": "US"
},

{
   "date": "2023-10-31",
   "note": "Luxury Penthouse with Ocean View in South Mumbai",
   "rappel_hour": "16:00",
   "country": "India",
   "mail_specified": "contact@realestate-example.com",
   "city": "Mumbai",
   "description": "Spectacular 4-bedroom penthouse with panoramic ocean views in South Mumbai.",
   "full_address": "123 Marine Drive, Mumbai 400002",
   "document_version": 1,
   "title": "Penthouse in Mumbai",
   "date_timestamp": 1667260800,
   "zip_code": "400002",
   "archived": False,
   "datetime": "2023-10-31 16:00:00",
   "expired": False,
   "file": "property4.pdf",
   "province": "Maharashtra",
   "category_id": "4",
   "last_update_timestamp": 1667260800,
   "street": "Marine Drive",
   "price": 25000000.0,
   "particulier": True,
   "id": "property-4",
   "state_id": "MH",
   "lang": "en",
   "owner_tel": "+91 1234567890",
   "rappel_date": "2023-11-10",
   "rappel_date_timestamp": 1678684800,
   "last_update_date": "2023-10-31",
   "m_2": 350,
   "website": "www.realestate-example.com",
   "tel_specified": True,
   "owner_name": "Raj Patel",
   "last_update_datetime": "2023-10-31 16:00:00",
   "created_by": "Sonia Gupta",
   "picture": "picture4.jpg",
   "url": "www.realestate-example.com/property-4",
   "address_number": "123",
   "cert_peb_specified": True,
   "sale": True,
   "deleted": False,
   "province_id": "MH",
   "category": "Penthouse",
   "website_id": "2",
   "country_id": "IN"
},

{
   "date": "2023-10-31",
   "note": "Appartement moderne au cœur de Douala",
   "rappel_hour": "15:30",
   "country": "Cameroun",
   "mail_specified": "contact@immobilier-example.com",
   "city": "Douala",
   "description": "Bel appartement de 2 chambres au centre de Douala.",
   "full_address": "123 Rue de Douala, Douala",
   "document_version": 1,
   "title": "Appartement à Douala",
   "date_timestamp": 1667260800,
   "zip_code": "N/A",
   "archived": False,
   "datetime": "2023-10-31 15:30:00",
   "expired": False,
   "file": "property5.pdf",
   "province": "Littoral",
   "category_id": "5",
   "last_update_timestamp": 1667260800,
   "street": "Rue de Douala",
   "price": 300000.0,
   "particulier": True,
   "id": "property-5",
   "state_id": "CM",
   "lang": "fr",
   "owner_tel": "+237 6X XX XX XX",
   "rappel_date": "2023-11-10",
   "rappel_date_timestamp": 1678684800,
   "last_update_date": "2023-10-31",
   "m_2": 120,
   "website": "www.immobilier-example.com",
   "tel_specified": True,
   "owner_name": "Amina Njoh",
   "last_update_datetime": "2023-10-31 15:30:00",
   "created_by": "Samuel Mboma",
   "picture": "picture5.jpg",
   "url": "www.immobilier-example.com/property-5",
   "address_number": "123",
   "cert_peb_specified": True,
   "sale": True,
   "deleted": False,
   "province_id": "LT",
   "category": "Appartement",
   "website_id": "1",
   "country_id": "CM"
},

{
   "date": "2023-10-31",
   "note": "Hermosa Casa en las Colinas de Caracas",
   "rappel_hour": "14:30",
   "country": "Venezuela",
   "mail_specified": "contacto@bienesraices-ejemplo.com",
   "city": "Caracas",
   "description": "Espectacular casa de 4 habitaciones con vistas a la ciudad en las colinas de Caracas.",
   "full_address": "123 Calle Caracas, Caracas",
   "document_version": 1,
   "title": "Casa en Caracas",
   "date_timestamp": 1667260800,
   "zip_code": "N/A",
   "archived": False,
   "datetime": "2023-10-31 14:30:00",
   "expired": False,
   "file": "property6.pdf",
   "province": "Distrito Capital",
   "category_id": "6",
   "last_update_timestamp": 1667260800,
   "street": "Calle Caracas",
   "price": 450000.0,
   "particulier": True,
   "id": "property-6",
   "state_id": "VE",
   "lang": "es",
   "owner_tel": "+58 XX XX XX XX",
   "rappel_date": "2023-11-15",
   "rappel_date_timestamp": 1678684800,
   "last_update_date": "2023-10-31",
   "m_2": 250,
   "website": "www.bienesraices-ejemplo.com",
   "tel_specified": True,
   "owner_name": "Luisa Rodriguez",
   "last_update_datetime": "2023-10-31 14:30:00",
   "created_by": "Carlos Pérez",
   "picture": "picture6.jpg",
   "url": "www.bienesraices-ejemplo.com/property-6",
   "address_number": "123",
   "cert_peb_specified": True,
   "sale": True,
   "deleted": False,
   "province_id": "DC",
   "category": "Casa",
   "website_id": "1",
   "country_id": "VE"
},
{
   "date": "2023-10-31",
   "note": "Moderno Apartamento en el Centro de Beijing",
   "rappel_hour": "16:00",
   "country": "China",
   "mail_specified": "contacto@inmobiliaria-ejemplo.com",
   "city": "Beijing",
   "description": "Espectacular apartamento de 3 habitaciones con vistas a la ciudad en el centro de Beijing.",
   "full_address": "123 Calle Beijing, Beijing",
   "document_version": 1,
   "title": "Apartamento en Beijing",
   "date_timestamp": 1667260800,
   "zip_code": "N/A",
   "archived": False,
   "datetime": "2023-10-31 16:00:00",
   "expired": False,
   "file": "property7.pdf",
   "province": "Pekín",
   "category_id": "7",
   "last_update_timestamp": 1667260800,
   "street": "Calle Beijing",
   "price": 800000.0,
   "particulier": True,
   "id": "property-7",
   "state_id": "CN",
   "lang": "es",
   "owner_tel": "+86 XX XX XX XX",
   "rappel_date": "2023-11-10",
   "rappel_date_timestamp": 1678684800,
   "last_update_date": "2023-10-31",
   "m_2": 150,
   "website": "www.inmobiliaria-ejemplo.com",
   "tel_specified": True,
   "owner_name": "Liu Wei",
   "last_update_datetime": "2023-10-31 16:00:00",
   "created_by": "Zhang Wei",
   "picture": "picture7.jpg",
   "url": "www.inmobiliaria-ejemplo.com/property-7",
   "address_number": "123",
   "cert_peb_specified": True,
   "sale": True,
   "deleted": False,
   "province_id": "PEK",
   "category": "Apartamento",
   "website_id": "1",
   "country_id": "CN"
},
{
   "date": "2023-10-31",
   "note": "Harika Boğaz Manzaralı Lüks Daire",
   "rappel_hour": "15:30",
   "country": "Türkiye",
   "mail_specified": "iletisim@emlak-ornek.com",
   "city": "İstanbul",
   "description": "Boğaz manzaralı, 3 yatak odalı lüks daire, İstanbul'un merkezinde.",
   "full_address": "123 İstanbul Caddesi, İstanbul",
   "document_version": 1,
   "title": "İstanbul'da Daire",
   "date_timestamp": 1667260800,
   "zip_code": "N/A",
   "archived": False,
   "datetime": "2023-10-31 15:30:00",
   "expired": False,
   "file": "property8.pdf",
   "province": "İstanbul",
   "category_id": "8",
   "last_update_timestamp": 1667260800,
   "street": "İstanbul Caddesi",
   "price": 900000.0,
   "particulier": True,
   "id": "property-8",
   "state_id": "TR",
   "lang": "tr",
   "owner_tel": "+90 XX XX XX XX",
   "rappel_date": "2023-11-10",
   "rappel_date_timestamp": 1678684800,
   "last_update_date": "2023-10-31",
   "m_2": 180,
   "website": "www.emlak-ornek.com",
   "tel_specified": True,
   "owner_name": "Fatma Yılmaz",
   "last_update_datetime": "2023-10-31 15:30:00",
   "created_by": "Mehmet Arslan",
   "picture": "picture8.jpg",
   "url": "www.emlak-ornek.com/property-8",
   "address_number": "123",
   "cert_peb_specified": True,
   "sale": True,
   "deleted": False,
   "province_id": "IST",
   "category": "Daire",
   "website_id": "1",
   "country_id": "TR"
}
]

#flask init
from flask import Flask, jsonify, render_template
app = Flask(__name__)

@app.route('/1')
def home():
    return render_template('model.html', objects=objects)

@app.route('/2')
def home2():
    return render_template('model2.html', objects=objects)

@app.route('/')
def home3():
    return render_template('model.html', objects=objects)

#run
if __name__ == "__main__":
    app.run(host="0.0.0.0")
